"""PDF export of a single incident report.

Structured the way a regulator or auditor would read it: incident facts,
scope (data, systems, activities, jurisdictions), severity, notification
obligations with their deadlines and status, the response checklist,
and the timeline. Mirrors the ReportLab pattern in Projects 2 and 3 for
visual consistency across the portfolio.
"""

# escape() only replaces &, < and > in a string we produce; nothing is parsed
# as XML, so bandit's B406 (XML parsing attacks) doesn't apply.
from xml.sax.saxutils import escape as xml_escape  # nosec B406

from django.conf import settings
from django.http import HttpResponse
from django.utils import timezone

from .deadlines import BUSINESS_DAY_CAVEAT
from .severity import SEVERITY_DISCLAIMER

EXPORT_BASENAME = "Incident-Report"

LEGAL_DISCLAIMER = (
    "This report was generated by a portfolio/demonstration tool about a fictional company "
    "and does not constitute legal advice. Notification obligations shown are the output of "
    "simplified rules; confirm every obligation with qualified counsel."
)

SEVERITY_COLORS = {
    "low": "#1E7A34",
    "medium": "#8A5A00",
    "high": "#B3261E",
    "critical": "#7A0E0E",
}

HEADER_BG = "#1F2A44"
GRID = "#CCCCCC"
ZEBRA = "#F5F6F8"


def _p(text, style):
    # reportlab's Paragraph parses a small XML-like markup language, so any
    # value we didn't write ourselves is escaped first — otherwise a "<" or
    # "&" in a free-text field would be swallowed or read as a tag. Newlines
    # become <br/> only after escaping, so they're the one markup we add.
    from reportlab.platypus import Paragraph

    return Paragraph(xml_escape(str(text)).replace("\n", "<br/>"), style)


def _fmt(dt) -> str:
    return dt.strftime("%Y-%m-%d %H:%M UTC") if dt else "—"


def export_pdf(row) -> HttpResponse:
    """`row` is a views.IncidentRow: the incident plus its computed
    severity and obligations, so the PDF shows exactly what the detail
    page shows."""
    # Imported lazily so the rest of the app runs even where reportlab
    # isn't installed; only this route pays the import cost.
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    incident = row.incident
    generated_at = timezone.now()
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        f'attachment; filename="{EXPORT_BASENAME}-{incident.reference}.pdf"'
    )

    doc = SimpleDocTemplate(
        response,  # type: ignore[arg-type]
        pagesize=letter,
        leftMargin=0.6 * inch,
        rightMargin=0.6 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.5 * inch,
        title=f"{settings.SITE_TITLE} — {incident.reference}",
    )

    styles = getSampleStyleSheet()
    body = styles["Normal"]
    small = ParagraphStyle("small", parent=body, fontSize=8.5, leading=10.5)
    section = ParagraphStyle("section", parent=styles["Heading2"], spaceBefore=14, spaceAfter=4)
    label = ParagraphStyle("label", parent=small, fontName="Helvetica-Bold")
    header_cell = ParagraphStyle("headerCell", parent=label, textColor=colors.white)
    disclaimer = ParagraphStyle(
        "disclaimer",
        parent=body,
        fontSize=8.5,
        textColor=colors.grey,
        borderColor=colors.HexColor(GRID),
        borderWidth=0.5,
        borderPadding=8,
    )

    def table(header, rows, widths):
        data = [[_p(h, header_cell) for h in header]]
        data += [
            [cell if not isinstance(cell, str) else _p(cell, small) for cell in r] for r in rows
        ]
        t = Table(data, colWidths=[w * inch for w in widths], repeatRows=1)
        t.setStyle(
            TableStyle(  # type: ignore[arg-type]
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(HEADER_BG)),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor(GRID)),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [colors.white, colors.HexColor(ZEBRA)],
                    ),
                ]
            )
        )
        return t

    severity = row.severity
    elements = [
        Paragraph(settings.SITE_TITLE, styles["Title"]),
        Paragraph("Security Incident Report", styles["Heading2"]),
        _p(f"{incident.reference} — {incident.title}", body),
        _p(f"Generated {_fmt(generated_at)} — NimbusCart (fictional company)", small),
        Spacer(1, 0.1 * inch),
    ]

    # 1. Incident facts
    elements.append(Paragraph("1. Incident summary", section))
    elements.append(_p(incident.summary, body))
    elements.append(Spacer(1, 0.08 * inch))
    facts = [
        ["Type", incident.get_incident_type_display()],
        ["Occurred", _fmt(incident.occurred_at)],
        ["Discovered", _fmt(incident.discovered_at)],
        ["Containment", incident.get_containment_status_display()],
        ["Risk to individuals (team assessment)", incident.get_risk_to_individuals_display()],
        [
            "Encryption",
            (
                "Encrypted; key compromised"
                if incident.data_encrypted and incident.encryption_key_compromised
                else (
                    "Encrypted; key not compromised"
                    if incident.data_encrypted
                    else "Not encrypted"
                )
            ),
        ],
    ]
    elements.append(table(["Field", "Value"], facts, [2.4, 4.9]))

    # 2. Scope
    elements.append(Paragraph("2. Scope", section))
    scope = [
        [
            "Data categories",
            ", ".join(c.name for c in incident.affected_data_categories.all())
            or "None recorded",
        ],
        [
            "Systems",
            ", ".join(s.name for s in incident.affected_systems.all()) or "None recorded",
        ],
        [
            "Processing activities (ROPA)",
            ", ".join(a.name for a in incident.affected_activities.all()) or "None recorded",
        ],
    ]
    for impact in incident.jurisdiction_impacts.all():
        scope.append(
            [f"Individuals — {impact.get_jurisdiction_display()}", f"{impact.individuals:,}"]
        )
    scope.append(["Individuals — total", f"{incident.total_individuals:,}"])
    elements.append(table(["Item", "Detail"], scope, [2.4, 4.9]))

    # 3. Severity
    elements.append(Paragraph("3. Severity (internal model)", section))
    color = SEVERITY_COLORS[severity.level.value]
    elements.append(
        Paragraph(
            f'<font color="{color}"><b>{severity.level.label}</b></font> &mdash; score {severity.score}',
            body,
        )
    )
    elements.append(
        table(
            ["Factor", "Points"],
            [[f.label, f"{f.points:+d}"] for f in severity.factors],
            [6.3, 1.0],
        )
    )
    elements.append(Spacer(1, 0.05 * inch))
    elements.append(Paragraph(SEVERITY_DISCLAIMER, disclaimer))

    # 4. Obligations
    elements.append(Paragraph("4. Notification &amp; related obligations", section))
    obligation_rows = []
    for o in row.obligations:
        r = o.requirement
        due = _fmt(o.due_at) if o.due_at else r.deadline_text
        if o.due_is_projected:
            due += " (projected)"
        status = o.status_label
        if o.sent_at:
            status += f" {_fmt(o.sent_at)}" + (" (late)" if o.sent_late else "")
        elif o.countdown:
            status += f" — {o.countdown.label}"
        verification = "" if r.is_verified else " [UNVERIFIED — see legal sources]"
        obligation_rows.append(
            [
                f"{r.get_framework_display()}{verification}",
                f"{r.title}\nTo: {r.recipient}\n{r.citation}",
                due,
                status,
                " ".join(o.reasons),
            ]
        )
    elements.append(
        table(
            ["Framework", "Obligation", "Deadline", "Status", "Why"],
            obligation_rows,
            [1.2, 1.9, 1.3, 1.2, 1.7],
        )
    )
    elements.append(Spacer(1, 0.05 * inch))
    elements.append(_p(BUSINESS_DAY_CAVEAT, small))

    # 5. Checklist
    elements.append(Paragraph("5. Response checklist", section))
    items = list(incident.checklist_items.all())
    if items:
        elements.append(
            table(
                ["Phase", "Task", "Owner", "Status"],
                [[i.phase, i.title, i.owner, i.get_status_display()] for i in items],
                [1.1, 3.8, 1.4, 1.0],
            )
        )
    else:
        elements.append(_p("No checklist items.", body))

    # 6. Timeline
    elements.append(Paragraph("6. Timeline", section))
    events = list(incident.timeline_events.all())
    if events:
        elements.append(
            table(
                ["When", "Event"],
                [[_fmt(e.occurred_at), e.description] for e in events],
                [1.6, 5.7],
            )
        )
    else:
        elements.append(_p("No timeline events recorded.", body))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(LEGAL_DISCLAIMER, disclaimer))

    doc.build(elements)
    return response
