"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from django.utils.csp import CSP

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

_ON_VERCEL = bool(os.environ.get("VERCEL"))
# Read by incidents/throttling.py to decide which client-IP header to trust.
RUNNING_ON_VERCEL = _ON_VERCEL

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True only for local development. On Vercel it defaults to
# False, so forgetting to set DJANGO_DEBUG can never expose debug pages
# (settings, stack traces, SQL) on the public deployment.
DEBUG = os.environ.get("DJANGO_DEBUG", "False" if _ON_VERCEL else "True") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment so a real key never has to live in source
# control. The throwaway fallback is only ever used with DEBUG on; with
# DEBUG off a missing key stops the app from starting instead of silently
# signing sessions and CSRF tokens with a key published in this repo.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DEBUG is off — see .env.example."
        )
    # Dev-only fallback, unreachable with DEBUG off (see above) — bandit B105.
    SECRET_KEY = (
        "django-insecure-dev-only-8x#h3f!q9k2m$w7z@r5t1v6n0y4b_incident+demo"  # nosec B105
    )

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]

# Vercel sets these at runtime — VERCEL_URL to the *current deployment's*
# unique hostname (a new one every deploy), VERCEL_PROJECT_PRODUCTION_URL
# to the stable production alias (e.g. incident-breach-response.vercel.app).
# Neither is known in advance, so they can't just go in
# DJANGO_ALLOWED_HOSTS — trust both automatically when present. A custom
# domain still needs to be added via DJANGO_ALLOWED_HOSTS.
_vercel_hosts = [
    h
    for h in (
        os.environ.get("VERCEL_URL"),
        os.environ.get("VERCEL_PROJECT_PRODUCTION_URL"),
    )
    if h
]
if _vercel_hosts:
    ALLOWED_HOSTS.extend(_vercel_hosts)
    CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in _vercel_hosts]
else:
    CSRF_TRUSTED_ORIGINS = [
        o.strip()
        for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
        if o.strip()
    ]

# Vercel (like most serverless/PaaS hosts) terminates TLS at the edge and
# forwards requests to the app over plain HTTP with this header set —
# without it Django can't tell the request was actually HTTPS, which
# breaks CSRF and secure-cookie checks.
if _ON_VERCEL:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Belt-and-suspenders production hardening. Vercel already forces HTTPS
# and sends HSTS/X-Content-Type-Options/X-Frame-Options at the edge for
# every deployment, so none of this is filling a gap there today — it's
# here so the app is still correctly configured if it's ever hosted
# somewhere that doesn't do that for you. `manage.py check --deploy` was
# used to find this list.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "incidents",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves static files directly from the app process. Vercel's
    # serverless functions have no separate static file server and no
    # persistent disk to run `collectstatic` into ahead of time, so
    # WhiteNoise (with WHITENOISE_USE_FINDERS below) serves them straight
    # from the source directories on every request — simplest thing that
    # works for this app's tiny CSS footprint.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
]

# Content-Security-Policy (built into Django 6): only this app's own
# scripts, styles and images may load, no inline code runs, and no other
# site may frame the pages. The templates have no inline <script> or
# style="" attributes, and neither do the Django admin's, so the policy can
# stay strict — it's the backstop if an escaping bug ever lets markup
# through into a page.
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "script-src": [CSP.SELF],
    "style-src": [CSP.SELF],
    "img-src": [CSP.SELF, "data:"],
    "object-src": [CSP.NONE],
    "base-uri": [CSP.NONE],
    "form-action": [CSP.SELF],
    "frame-ancestors": [CSP.NONE],
}

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite locally (zero setup, matches the README's local-dev instructions).
# In production — Vercel's serverless functions have no persistent disk,
# so a SQLite file wouldn't survive between requests — set DATABASE_URL
# (Vercel's Postgres/Neon integration injects POSTGRES_URL automatically;
# either name is read here) to switch to Postgres with no code changes.
_database_url = os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL")

if _database_url:
    DATABASES = {"default": dj_database_url.parse(_database_url, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }

# Cache — which is where the rate limits (incidents/views.py, admin login)
# keep their counters. Django's default in-memory cache is per process, and
# on Vercel every serverless instance is its own process, so each one would
# count separately and the limits would barely apply. With a real database
# configured, the counters live in a Postgres table instead, shared by every
# instance. The table is created by `manage.py createcachetable` (see the
# README's deployment steps; the test runner creates it automatically).
if _database_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "django_cache",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}
# Serve straight from STATICFILES_DIRS instead of requiring collectstatic
# to have run first — this app's static payload is one CSS file, so the
# (real, but here irrelevant) performance cost of skipping the
# manifest/hashing is a non-issue, and it keeps `manage.py runserver` and
# `manage.py test` working with zero build step, matching local dev.
WHITENOISE_USE_FINDERS = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Site-wide display name, used in the base template <title> and the
# incident PDF export. Kept as a setting rather than hard-coded so it only
# needs to change in one place.
SITE_TITLE = "Incident-Breach-Response"
