# Generated by Django 6.1.1 on 2026-09-26 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, max_length=5000)),
                (
                    "is_special_category",
                    models.BooleanField(
                        default=False,
                        help_text="Falls within LGPD Art. 5, II ('dado pessoal sensível') / GDPR Art. 9(1) (e.g. health, biometric, genetic data).",
                    ),
                ),
                (
                    "is_financial",
                    models.BooleanField(
                        default=False,
                        help_text="Financial data — one of the ANPD RCIS Art. 5 criteria (inciso III).",
                    ),
                ),
                (
                    "is_authentication",
                    models.BooleanField(
                        default=False,
                        help_text="System authentication data — one of the ANPD RCIS Art. 5 criteria (inciso IV).",
                    ),
                ),
                (
                    "is_ca_breach_element",
                    models.BooleanField(
                        default=False,
                        help_text="As NimbusCart stores it, this category meets a Cal. Civ. Code § 1798.82(h) definition of 'personal information' — name combined with a listed data element (SSN, government ID number, financial account + access code, medical or health insurance information, biometric, ALPR or genetic data), or a username/email with a password or security Q&A.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Data categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("owner_team", models.CharField(max_length=120)),
                (
                    "hosting",
                    models.CharField(
                        blank=True,
                        help_text="Where it runs, e.g. 'AWS (us-east-1)' or a vendor name.",
                        max_length=150,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=5000)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reference", models.CharField(editable=False, max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "summary",
                    models.TextField(
                        help_text="What happened, as currently understood.", max_length=5000
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("unauthorized_access", "Unauthorized access / intrusion"),
                            ("ransomware", "Ransomware / malware"),
                            ("misdirected", "Misdirected disclosure (wrong recipient)"),
                            ("lost_device", "Lost or stolen device"),
                            ("vendor", "Vendor / processor incident"),
                            ("insider", "Insider misuse"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        blank=True, help_text="When the incident started, if known.", null=True
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        help_text="When NimbusCart became aware that the incident affected personal data. Every deadline countdown starts here."
                    ),
                ),
                (
                    "containment_status",
                    models.CharField(
                        choices=[
                            ("investigating", "Investigating"),
                            ("ongoing", "Active — not contained"),
                            ("contained", "Contained"),
                            ("resolved", "Resolved"),
                        ],
                        default="investigating",
                        max_length=20,
                    ),
                ),
                (
                    "risk_to_individuals",
                    models.CharField(
                        choices=[
                            ("unlikely", "Unlikely to result in a risk"),
                            ("risk", "Likely to result in a risk"),
                            ("high", "Likely to result in a high risk"),
                        ],
                        default="risk",
                        help_text="The response team's documented risk assessment for affected individuals. Drives the GDPR Art. 33/34 and LGPD Art. 48 tests.",
                        max_length=20,
                    ),
                ),
                (
                    "data_encrypted",
                    models.BooleanField(
                        default=False,
                        help_text="The affected data was encrypted/unintelligible to the attacker.",
                    ),
                ),
                (
                    "encryption_key_compromised",
                    models.BooleanField(
                        default=False,
                        help_text="The key or credential needed to decrypt it was also exposed.",
                    ),
                ),
                (
                    "involves_vulnerable_individuals",
                    models.BooleanField(
                        default=False,
                        help_text="Affects data of children, adolescents or elderly people (ANPD RCIS Art. 5, II).",
                    ),
                ),
                (
                    "involves_confidential_data",
                    models.BooleanField(
                        default=False,
                        help_text="Affects data under legal, judicial or professional secrecy (ANPD RCIS Art. 5, V).",
                    ),
                ),
                (
                    "is_large_scale",
                    models.BooleanField(
                        default=False,
                        help_text="The team judges this a large-scale incident (ANPD RCIS Art. 5, VI and §2: number of people, data volume, duration, frequency, geographic reach).",
                    ),
                ),
                (
                    "controller_is_small_agent",
                    models.BooleanField(
                        default=False,
                        help_text="The controller qualifies as a small-scale processing agent under ANPD Resolução CD/ANPD nº 2/2022 (LGPD communication deadlines count double).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affected_data_categories",
                    models.ManyToManyField(
                        blank=True, related_name="incidents", to="incidents.datacategory"
                    ),
                ),
            ],
            options={
                "ordering": ("-discovered_at",),
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("phase", models.CharField(blank=True, max_length=40)),
                ("owner", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To do"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("n_a", "Not applicable"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="LegalRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Stable identifier the applicability logic in obligations.py is keyed on.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("lgpd", "LGPD (Brazil)"),
                            ("gdpr", "GDPR (EU/EEA)"),
                            (
                                "ca_breach",
                                "California breach-notification law (Civ. Code § 1798.82)",
                            ),
                            ("ccpa", "CCPA/CPRA (California)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("notification", "Notification"),
                            ("record", "Internal record-keeping"),
                            ("exposure", "Liability exposure (no notice owed)"),
                        ],
                        default="notification",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "recipient",
                    models.CharField(
                        help_text="Who must be notified, e.g. 'ANPD' or 'Affected data subjects'.",
                        max_length=200,
                    ),
                ),
                (
                    "trigger_summary",
                    models.TextField(
                        help_text="When this obligation is triggered, in plain language.",
                        max_length=5000,
                    ),
                ),
                (
                    "deadline_unit",
                    models.CharField(
                        choices=[
                            ("none", "No fixed deadline"),
                            ("hours", "Hours"),
                            ("calendar_days", "Calendar days"),
                            ("business_days", "Business days"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("deadline_value", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "deadline_text",
                    models.CharField(
                        help_text="The deadline as the source words it, e.g. 'without undue delay'.",
                        max_length=300,
                    ),
                ),
                ("citation", models.CharField(max_length=200)),
                ("source_url", models.URLField(blank=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Check only after this requirement has been verified against the primary source.",
                    ),
                ),
                ("verified_on", models.DateField(blank=True, null=True)),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True,
                        help_text="What was checked, or a 'TODO: VERIFY ...' note if not yet verified.",
                        max_length=5000,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "deadline_runs_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty if the deadline runs from discovery. Set it when the clock starts at another notice instead (e.g. California's AG copy runs from the consumer notice).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_requirements",
                        to="incidents.legalrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "code"),
            },
        ),
        migrations.CreateModel(
            name="ProcessingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("department", models.CharField(max_length=120)),
                ("purpose", models.TextField(max_length=5000)),
                (
                    "data_categories",
                    models.ManyToManyField(
                        related_name="activities", to="incidents.datacategory"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Processing activities",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="incident",
            name="affected_activities",
            field=models.ManyToManyField(
                blank=True, related_name="incidents", to="incidents.processingactivity"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="affected_systems",
            field=models.ManyToManyField(
                blank=True, related_name="incidents", to="incidents.system"
            ),
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("description", models.TextField(max_length=5000)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="JurisdictionImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("BR", "Brazil"),
                            ("EU", "EU / EEA"),
                            ("US-CA", "California (US)"),
                            ("US-OTHER", "Other US states (not evaluated)"),
                            ("OTHER", "Rest of world (not evaluated)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "individuals",
                    models.PositiveIntegerField(
                        help_text="Number of affected individuals (best estimate)."
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jurisdiction_impacts",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ("jurisdiction",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident", "jurisdiction"),
                        name="unique_jurisdiction_per_incident",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sent_at", models.DateTimeField()),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Protocol/ticket number, if the recipient issued one.",
                        max_length=120,
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=5000)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_records",
                        to="incidents.incident",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_records",
                        to="incidents.legalrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ("sent_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident", "requirement"), name="unique_record_per_requirement"
                    )
                ],
            },
        ),
    ]
