# Generated by Django 6.1.1 on 2026-09-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacategory",
            name="is_ccpa_150_element",
            field=models.BooleanField(
                default=False,
                help_text="As NimbusCart stores it, this category is 'personal information' for the CCPA private right of action (Cal. Civ. Code § 1798.150(a)(1)): name combined with an element listed in § 1798.81.5(d)(1)(A) (SSN, government ID number, financial account + access code, medical or health insurance information, biometric or genetic data), or an email address with a password or security Q&A.",
            ),
        ),
    ]
